//go:build !ignore_autogenerated_conversions
// +build !ignore_autogenerated_conversions

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	v1beta2 "sigs.k8s.io/cluster-api-provider-aws/bootstrap/eks/api/v1beta2"
	apiv1beta1 "sigs.k8s.io/cluster-api/api/v1beta1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DiskSetup)(nil), (*v1beta2.DiskSetup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_DiskSetup_To_v1beta2_DiskSetup(a.(*DiskSetup), b.(*v1beta2.DiskSetup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.DiskSetup)(nil), (*DiskSetup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_DiskSetup_To_v1beta1_DiskSetup(a.(*v1beta2.DiskSetup), b.(*DiskSetup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EKSConfig)(nil), (*v1beta2.EKSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EKSConfig_To_v1beta2_EKSConfig(a.(*EKSConfig), b.(*v1beta2.EKSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EKSConfig)(nil), (*EKSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EKSConfig_To_v1beta1_EKSConfig(a.(*v1beta2.EKSConfig), b.(*EKSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EKSConfigList)(nil), (*v1beta2.EKSConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EKSConfigList_To_v1beta2_EKSConfigList(a.(*EKSConfigList), b.(*v1beta2.EKSConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EKSConfigList)(nil), (*EKSConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EKSConfigList_To_v1beta1_EKSConfigList(a.(*v1beta2.EKSConfigList), b.(*EKSConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EKSConfigSpec)(nil), (*v1beta2.EKSConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EKSConfigSpec_To_v1beta2_EKSConfigSpec(a.(*EKSConfigSpec), b.(*v1beta2.EKSConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EKSConfigSpec)(nil), (*EKSConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EKSConfigSpec_To_v1beta1_EKSConfigSpec(a.(*v1beta2.EKSConfigSpec), b.(*EKSConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EKSConfigStatus)(nil), (*v1beta2.EKSConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EKSConfigStatus_To_v1beta2_EKSConfigStatus(a.(*EKSConfigStatus), b.(*v1beta2.EKSConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EKSConfigStatus)(nil), (*EKSConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EKSConfigStatus_To_v1beta1_EKSConfigStatus(a.(*v1beta2.EKSConfigStatus), b.(*EKSConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EKSConfigTemplate)(nil), (*v1beta2.EKSConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EKSConfigTemplate_To_v1beta2_EKSConfigTemplate(a.(*EKSConfigTemplate), b.(*v1beta2.EKSConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EKSConfigTemplate)(nil), (*EKSConfigTemplate)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EKSConfigTemplate_To_v1beta1_EKSConfigTemplate(a.(*v1beta2.EKSConfigTemplate), b.(*EKSConfigTemplate), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EKSConfigTemplateList)(nil), (*v1beta2.EKSConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EKSConfigTemplateList_To_v1beta2_EKSConfigTemplateList(a.(*EKSConfigTemplateList), b.(*v1beta2.EKSConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EKSConfigTemplateList)(nil), (*EKSConfigTemplateList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EKSConfigTemplateList_To_v1beta1_EKSConfigTemplateList(a.(*v1beta2.EKSConfigTemplateList), b.(*EKSConfigTemplateList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EKSConfigTemplateResource)(nil), (*v1beta2.EKSConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EKSConfigTemplateResource_To_v1beta2_EKSConfigTemplateResource(a.(*EKSConfigTemplateResource), b.(*v1beta2.EKSConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EKSConfigTemplateResource)(nil), (*EKSConfigTemplateResource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EKSConfigTemplateResource_To_v1beta1_EKSConfigTemplateResource(a.(*v1beta2.EKSConfigTemplateResource), b.(*EKSConfigTemplateResource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*EKSConfigTemplateSpec)(nil), (*v1beta2.EKSConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_EKSConfigTemplateSpec_To_v1beta2_EKSConfigTemplateSpec(a.(*EKSConfigTemplateSpec), b.(*v1beta2.EKSConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.EKSConfigTemplateSpec)(nil), (*EKSConfigTemplateSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_EKSConfigTemplateSpec_To_v1beta1_EKSConfigTemplateSpec(a.(*v1beta2.EKSConfigTemplateSpec), b.(*EKSConfigTemplateSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*File)(nil), (*v1beta2.File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_File_To_v1beta2_File(a.(*File), b.(*v1beta2.File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.File)(nil), (*File)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_File_To_v1beta1_File(a.(*v1beta2.File), b.(*File), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FileSource)(nil), (*v1beta2.FileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_FileSource_To_v1beta2_FileSource(a.(*FileSource), b.(*v1beta2.FileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.FileSource)(nil), (*FileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_FileSource_To_v1beta1_FileSource(a.(*v1beta2.FileSource), b.(*FileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Filesystem)(nil), (*v1beta2.Filesystem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Filesystem_To_v1beta2_Filesystem(a.(*Filesystem), b.(*v1beta2.Filesystem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.Filesystem)(nil), (*Filesystem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Filesystem_To_v1beta1_Filesystem(a.(*v1beta2.Filesystem), b.(*Filesystem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NTP)(nil), (*v1beta2.NTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NTP_To_v1beta2_NTP(a.(*NTP), b.(*v1beta2.NTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.NTP)(nil), (*NTP)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_NTP_To_v1beta1_NTP(a.(*v1beta2.NTP), b.(*NTP), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Partition)(nil), (*v1beta2.Partition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_Partition_To_v1beta2_Partition(a.(*Partition), b.(*v1beta2.Partition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.Partition)(nil), (*Partition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_Partition_To_v1beta1_Partition(a.(*v1beta2.Partition), b.(*Partition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PasswdSource)(nil), (*v1beta2.PasswdSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PasswdSource_To_v1beta2_PasswdSource(a.(*PasswdSource), b.(*v1beta2.PasswdSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.PasswdSource)(nil), (*PasswdSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PasswdSource_To_v1beta1_PasswdSource(a.(*v1beta2.PasswdSource), b.(*PasswdSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PauseContainer)(nil), (*v1beta2.PauseContainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_PauseContainer_To_v1beta2_PauseContainer(a.(*PauseContainer), b.(*v1beta2.PauseContainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.PauseContainer)(nil), (*PauseContainer)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_PauseContainer_To_v1beta1_PauseContainer(a.(*v1beta2.PauseContainer), b.(*PauseContainer), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretFileSource)(nil), (*v1beta2.SecretFileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(a.(*SecretFileSource), b.(*v1beta2.SecretFileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.SecretFileSource)(nil), (*SecretFileSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(a.(*v1beta2.SecretFileSource), b.(*SecretFileSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretPasswdSource)(nil), (*v1beta2.SecretPasswdSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SecretPasswdSource_To_v1beta2_SecretPasswdSource(a.(*SecretPasswdSource), b.(*v1beta2.SecretPasswdSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.SecretPasswdSource)(nil), (*SecretPasswdSource)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_SecretPasswdSource_To_v1beta1_SecretPasswdSource(a.(*v1beta2.SecretPasswdSource), b.(*SecretPasswdSource), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*User)(nil), (*v1beta2.User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_User_To_v1beta2_User(a.(*User), b.(*v1beta2.User), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1beta2.User)(nil), (*User)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta2_User_To_v1beta1_User(a.(*v1beta2.User), b.(*User), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_DiskSetup_To_v1beta2_DiskSetup(in *DiskSetup, out *v1beta2.DiskSetup, s conversion.Scope) error {
	out.Partitions = *(*[]v1beta2.Partition)(unsafe.Pointer(&in.Partitions))
	out.Filesystems = *(*[]v1beta2.Filesystem)(unsafe.Pointer(&in.Filesystems))
	return nil
}

// Convert_v1beta1_DiskSetup_To_v1beta2_DiskSetup is an autogenerated conversion function.
func Convert_v1beta1_DiskSetup_To_v1beta2_DiskSetup(in *DiskSetup, out *v1beta2.DiskSetup, s conversion.Scope) error {
	return autoConvert_v1beta1_DiskSetup_To_v1beta2_DiskSetup(in, out, s)
}

func autoConvert_v1beta2_DiskSetup_To_v1beta1_DiskSetup(in *v1beta2.DiskSetup, out *DiskSetup, s conversion.Scope) error {
	out.Partitions = *(*[]Partition)(unsafe.Pointer(&in.Partitions))
	out.Filesystems = *(*[]Filesystem)(unsafe.Pointer(&in.Filesystems))
	return nil
}

// Convert_v1beta2_DiskSetup_To_v1beta1_DiskSetup is an autogenerated conversion function.
func Convert_v1beta2_DiskSetup_To_v1beta1_DiskSetup(in *v1beta2.DiskSetup, out *DiskSetup, s conversion.Scope) error {
	return autoConvert_v1beta2_DiskSetup_To_v1beta1_DiskSetup(in, out, s)
}

func autoConvert_v1beta1_EKSConfig_To_v1beta2_EKSConfig(in *EKSConfig, out *v1beta2.EKSConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_EKSConfigSpec_To_v1beta2_EKSConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_EKSConfigStatus_To_v1beta2_EKSConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_EKSConfig_To_v1beta2_EKSConfig is an autogenerated conversion function.
func Convert_v1beta1_EKSConfig_To_v1beta2_EKSConfig(in *EKSConfig, out *v1beta2.EKSConfig, s conversion.Scope) error {
	return autoConvert_v1beta1_EKSConfig_To_v1beta2_EKSConfig(in, out, s)
}

func autoConvert_v1beta2_EKSConfig_To_v1beta1_EKSConfig(in *v1beta2.EKSConfig, out *EKSConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_EKSConfigSpec_To_v1beta1_EKSConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta2_EKSConfigStatus_To_v1beta1_EKSConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_EKSConfig_To_v1beta1_EKSConfig is an autogenerated conversion function.
func Convert_v1beta2_EKSConfig_To_v1beta1_EKSConfig(in *v1beta2.EKSConfig, out *EKSConfig, s conversion.Scope) error {
	return autoConvert_v1beta2_EKSConfig_To_v1beta1_EKSConfig(in, out, s)
}

func autoConvert_v1beta1_EKSConfigList_To_v1beta2_EKSConfigList(in *EKSConfigList, out *v1beta2.EKSConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta2.EKSConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_EKSConfigList_To_v1beta2_EKSConfigList is an autogenerated conversion function.
func Convert_v1beta1_EKSConfigList_To_v1beta2_EKSConfigList(in *EKSConfigList, out *v1beta2.EKSConfigList, s conversion.Scope) error {
	return autoConvert_v1beta1_EKSConfigList_To_v1beta2_EKSConfigList(in, out, s)
}

func autoConvert_v1beta2_EKSConfigList_To_v1beta1_EKSConfigList(in *v1beta2.EKSConfigList, out *EKSConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]EKSConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta2_EKSConfigList_To_v1beta1_EKSConfigList is an autogenerated conversion function.
func Convert_v1beta2_EKSConfigList_To_v1beta1_EKSConfigList(in *v1beta2.EKSConfigList, out *EKSConfigList, s conversion.Scope) error {
	return autoConvert_v1beta2_EKSConfigList_To_v1beta1_EKSConfigList(in, out, s)
}

func autoConvert_v1beta1_EKSConfigSpec_To_v1beta2_EKSConfigSpec(in *EKSConfigSpec, out *v1beta2.EKSConfigSpec, s conversion.Scope) error {
	out.KubeletExtraArgs = *(*map[string]string)(unsafe.Pointer(&in.KubeletExtraArgs))
	out.ContainerRuntime = (*string)(unsafe.Pointer(in.ContainerRuntime))
	out.DNSClusterIP = (*string)(unsafe.Pointer(in.DNSClusterIP))
	out.DockerConfigJSON = (*string)(unsafe.Pointer(in.DockerConfigJSON))
	out.APIRetryAttempts = (*int)(unsafe.Pointer(in.APIRetryAttempts))
	out.PauseContainer = (*v1beta2.PauseContainer)(unsafe.Pointer(in.PauseContainer))
	out.UseMaxPods = (*bool)(unsafe.Pointer(in.UseMaxPods))
	out.ServiceIPV6Cidr = (*string)(unsafe.Pointer(in.ServiceIPV6Cidr))
	out.PreBootstrapCommands = *(*[]string)(unsafe.Pointer(&in.PreBootstrapCommands))
	out.PostBootstrapCommands = *(*[]string)(unsafe.Pointer(&in.PostBootstrapCommands))
	out.BootstrapCommandOverride = (*string)(unsafe.Pointer(in.BootstrapCommandOverride))
	out.Files = *(*[]v1beta2.File)(unsafe.Pointer(&in.Files))
	out.DiskSetup = (*v1beta2.DiskSetup)(unsafe.Pointer(in.DiskSetup))
	out.Mounts = *(*[]v1beta2.MountPoints)(unsafe.Pointer(&in.Mounts))
	out.Users = *(*[]v1beta2.User)(unsafe.Pointer(&in.Users))
	out.NTP = (*v1beta2.NTP)(unsafe.Pointer(in.NTP))
	return nil
}

// Convert_v1beta1_EKSConfigSpec_To_v1beta2_EKSConfigSpec is an autogenerated conversion function.
func Convert_v1beta1_EKSConfigSpec_To_v1beta2_EKSConfigSpec(in *EKSConfigSpec, out *v1beta2.EKSConfigSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_EKSConfigSpec_To_v1beta2_EKSConfigSpec(in, out, s)
}

func autoConvert_v1beta2_EKSConfigSpec_To_v1beta1_EKSConfigSpec(in *v1beta2.EKSConfigSpec, out *EKSConfigSpec, s conversion.Scope) error {
	out.KubeletExtraArgs = *(*map[string]string)(unsafe.Pointer(&in.KubeletExtraArgs))
	out.ContainerRuntime = (*string)(unsafe.Pointer(in.ContainerRuntime))
	out.DNSClusterIP = (*string)(unsafe.Pointer(in.DNSClusterIP))
	out.DockerConfigJSON = (*string)(unsafe.Pointer(in.DockerConfigJSON))
	out.APIRetryAttempts = (*int)(unsafe.Pointer(in.APIRetryAttempts))
	out.PauseContainer = (*PauseContainer)(unsafe.Pointer(in.PauseContainer))
	out.UseMaxPods = (*bool)(unsafe.Pointer(in.UseMaxPods))
	out.ServiceIPV6Cidr = (*string)(unsafe.Pointer(in.ServiceIPV6Cidr))
	out.PreBootstrapCommands = *(*[]string)(unsafe.Pointer(&in.PreBootstrapCommands))
	out.PostBootstrapCommands = *(*[]string)(unsafe.Pointer(&in.PostBootstrapCommands))
	out.BootstrapCommandOverride = (*string)(unsafe.Pointer(in.BootstrapCommandOverride))
	out.Files = *(*[]File)(unsafe.Pointer(&in.Files))
	out.DiskSetup = (*DiskSetup)(unsafe.Pointer(in.DiskSetup))
	out.Mounts = *(*[]MountPoints)(unsafe.Pointer(&in.Mounts))
	out.Users = *(*[]User)(unsafe.Pointer(&in.Users))
	out.NTP = (*NTP)(unsafe.Pointer(in.NTP))
	return nil
}

// Convert_v1beta2_EKSConfigSpec_To_v1beta1_EKSConfigSpec is an autogenerated conversion function.
func Convert_v1beta2_EKSConfigSpec_To_v1beta1_EKSConfigSpec(in *v1beta2.EKSConfigSpec, out *EKSConfigSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_EKSConfigSpec_To_v1beta1_EKSConfigSpec(in, out, s)
}

func autoConvert_v1beta1_EKSConfigStatus_To_v1beta2_EKSConfigStatus(in *EKSConfigStatus, out *v1beta2.EKSConfigStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	out.FailureReason = in.FailureReason
	out.FailureMessage = in.FailureMessage
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta1_EKSConfigStatus_To_v1beta2_EKSConfigStatus is an autogenerated conversion function.
func Convert_v1beta1_EKSConfigStatus_To_v1beta2_EKSConfigStatus(in *EKSConfigStatus, out *v1beta2.EKSConfigStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_EKSConfigStatus_To_v1beta2_EKSConfigStatus(in, out, s)
}

func autoConvert_v1beta2_EKSConfigStatus_To_v1beta1_EKSConfigStatus(in *v1beta2.EKSConfigStatus, out *EKSConfigStatus, s conversion.Scope) error {
	out.Ready = in.Ready
	out.DataSecretName = (*string)(unsafe.Pointer(in.DataSecretName))
	out.FailureReason = in.FailureReason
	out.FailureMessage = in.FailureMessage
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*apiv1beta1.Conditions)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1beta2_EKSConfigStatus_To_v1beta1_EKSConfigStatus is an autogenerated conversion function.
func Convert_v1beta2_EKSConfigStatus_To_v1beta1_EKSConfigStatus(in *v1beta2.EKSConfigStatus, out *EKSConfigStatus, s conversion.Scope) error {
	return autoConvert_v1beta2_EKSConfigStatus_To_v1beta1_EKSConfigStatus(in, out, s)
}

func autoConvert_v1beta1_EKSConfigTemplate_To_v1beta2_EKSConfigTemplate(in *EKSConfigTemplate, out *v1beta2.EKSConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_EKSConfigTemplateSpec_To_v1beta2_EKSConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_EKSConfigTemplate_To_v1beta2_EKSConfigTemplate is an autogenerated conversion function.
func Convert_v1beta1_EKSConfigTemplate_To_v1beta2_EKSConfigTemplate(in *EKSConfigTemplate, out *v1beta2.EKSConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1beta1_EKSConfigTemplate_To_v1beta2_EKSConfigTemplate(in, out, s)
}

func autoConvert_v1beta2_EKSConfigTemplate_To_v1beta1_EKSConfigTemplate(in *v1beta2.EKSConfigTemplate, out *EKSConfigTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta2_EKSConfigTemplateSpec_To_v1beta1_EKSConfigTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_EKSConfigTemplate_To_v1beta1_EKSConfigTemplate is an autogenerated conversion function.
func Convert_v1beta2_EKSConfigTemplate_To_v1beta1_EKSConfigTemplate(in *v1beta2.EKSConfigTemplate, out *EKSConfigTemplate, s conversion.Scope) error {
	return autoConvert_v1beta2_EKSConfigTemplate_To_v1beta1_EKSConfigTemplate(in, out, s)
}

func autoConvert_v1beta1_EKSConfigTemplateList_To_v1beta2_EKSConfigTemplateList(in *EKSConfigTemplateList, out *v1beta2.EKSConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]v1beta2.EKSConfigTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_EKSConfigTemplateList_To_v1beta2_EKSConfigTemplateList is an autogenerated conversion function.
func Convert_v1beta1_EKSConfigTemplateList_To_v1beta2_EKSConfigTemplateList(in *EKSConfigTemplateList, out *v1beta2.EKSConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta1_EKSConfigTemplateList_To_v1beta2_EKSConfigTemplateList(in, out, s)
}

func autoConvert_v1beta2_EKSConfigTemplateList_To_v1beta1_EKSConfigTemplateList(in *v1beta2.EKSConfigTemplateList, out *EKSConfigTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]EKSConfigTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta2_EKSConfigTemplateList_To_v1beta1_EKSConfigTemplateList is an autogenerated conversion function.
func Convert_v1beta2_EKSConfigTemplateList_To_v1beta1_EKSConfigTemplateList(in *v1beta2.EKSConfigTemplateList, out *EKSConfigTemplateList, s conversion.Scope) error {
	return autoConvert_v1beta2_EKSConfigTemplateList_To_v1beta1_EKSConfigTemplateList(in, out, s)
}

func autoConvert_v1beta1_EKSConfigTemplateResource_To_v1beta2_EKSConfigTemplateResource(in *EKSConfigTemplateResource, out *v1beta2.EKSConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta1_EKSConfigSpec_To_v1beta2_EKSConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_EKSConfigTemplateResource_To_v1beta2_EKSConfigTemplateResource is an autogenerated conversion function.
func Convert_v1beta1_EKSConfigTemplateResource_To_v1beta2_EKSConfigTemplateResource(in *EKSConfigTemplateResource, out *v1beta2.EKSConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta1_EKSConfigTemplateResource_To_v1beta2_EKSConfigTemplateResource(in, out, s)
}

func autoConvert_v1beta2_EKSConfigTemplateResource_To_v1beta1_EKSConfigTemplateResource(in *v1beta2.EKSConfigTemplateResource, out *EKSConfigTemplateResource, s conversion.Scope) error {
	if err := Convert_v1beta2_EKSConfigSpec_To_v1beta1_EKSConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_EKSConfigTemplateResource_To_v1beta1_EKSConfigTemplateResource is an autogenerated conversion function.
func Convert_v1beta2_EKSConfigTemplateResource_To_v1beta1_EKSConfigTemplateResource(in *v1beta2.EKSConfigTemplateResource, out *EKSConfigTemplateResource, s conversion.Scope) error {
	return autoConvert_v1beta2_EKSConfigTemplateResource_To_v1beta1_EKSConfigTemplateResource(in, out, s)
}

func autoConvert_v1beta1_EKSConfigTemplateSpec_To_v1beta2_EKSConfigTemplateSpec(in *EKSConfigTemplateSpec, out *v1beta2.EKSConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta1_EKSConfigTemplateResource_To_v1beta2_EKSConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_EKSConfigTemplateSpec_To_v1beta2_EKSConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1beta1_EKSConfigTemplateSpec_To_v1beta2_EKSConfigTemplateSpec(in *EKSConfigTemplateSpec, out *v1beta2.EKSConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_EKSConfigTemplateSpec_To_v1beta2_EKSConfigTemplateSpec(in, out, s)
}

func autoConvert_v1beta2_EKSConfigTemplateSpec_To_v1beta1_EKSConfigTemplateSpec(in *v1beta2.EKSConfigTemplateSpec, out *EKSConfigTemplateSpec, s conversion.Scope) error {
	if err := Convert_v1beta2_EKSConfigTemplateResource_To_v1beta1_EKSConfigTemplateResource(&in.Template, &out.Template, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_EKSConfigTemplateSpec_To_v1beta1_EKSConfigTemplateSpec is an autogenerated conversion function.
func Convert_v1beta2_EKSConfigTemplateSpec_To_v1beta1_EKSConfigTemplateSpec(in *v1beta2.EKSConfigTemplateSpec, out *EKSConfigTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1beta2_EKSConfigTemplateSpec_To_v1beta1_EKSConfigTemplateSpec(in, out, s)
}

func autoConvert_v1beta1_File_To_v1beta2_File(in *File, out *v1beta2.File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = v1beta2.Encoding(in.Encoding)
	out.Append = in.Append
	out.Content = in.Content
	out.ContentFrom = (*v1beta2.FileSource)(unsafe.Pointer(in.ContentFrom))
	return nil
}

// Convert_v1beta1_File_To_v1beta2_File is an autogenerated conversion function.
func Convert_v1beta1_File_To_v1beta2_File(in *File, out *v1beta2.File, s conversion.Scope) error {
	return autoConvert_v1beta1_File_To_v1beta2_File(in, out, s)
}

func autoConvert_v1beta2_File_To_v1beta1_File(in *v1beta2.File, out *File, s conversion.Scope) error {
	out.Path = in.Path
	out.Owner = in.Owner
	out.Permissions = in.Permissions
	out.Encoding = Encoding(in.Encoding)
	out.Append = in.Append
	out.Content = in.Content
	out.ContentFrom = (*FileSource)(unsafe.Pointer(in.ContentFrom))
	return nil
}

// Convert_v1beta2_File_To_v1beta1_File is an autogenerated conversion function.
func Convert_v1beta2_File_To_v1beta1_File(in *v1beta2.File, out *File, s conversion.Scope) error {
	return autoConvert_v1beta2_File_To_v1beta1_File(in, out, s)
}

func autoConvert_v1beta1_FileSource_To_v1beta2_FileSource(in *FileSource, out *v1beta2.FileSource, s conversion.Scope) error {
	if err := Convert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(&in.Secret, &out.Secret, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_FileSource_To_v1beta2_FileSource is an autogenerated conversion function.
func Convert_v1beta1_FileSource_To_v1beta2_FileSource(in *FileSource, out *v1beta2.FileSource, s conversion.Scope) error {
	return autoConvert_v1beta1_FileSource_To_v1beta2_FileSource(in, out, s)
}

func autoConvert_v1beta2_FileSource_To_v1beta1_FileSource(in *v1beta2.FileSource, out *FileSource, s conversion.Scope) error {
	if err := Convert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(&in.Secret, &out.Secret, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_FileSource_To_v1beta1_FileSource is an autogenerated conversion function.
func Convert_v1beta2_FileSource_To_v1beta1_FileSource(in *v1beta2.FileSource, out *FileSource, s conversion.Scope) error {
	return autoConvert_v1beta2_FileSource_To_v1beta1_FileSource(in, out, s)
}

func autoConvert_v1beta1_Filesystem_To_v1beta2_Filesystem(in *Filesystem, out *v1beta2.Filesystem, s conversion.Scope) error {
	out.Device = in.Device
	out.Filesystem = in.Filesystem
	out.Label = in.Label
	out.Partition = (*string)(unsafe.Pointer(in.Partition))
	out.Overwrite = (*bool)(unsafe.Pointer(in.Overwrite))
	out.ReplaceFS = (*string)(unsafe.Pointer(in.ReplaceFS))
	out.ExtraOpts = *(*[]string)(unsafe.Pointer(&in.ExtraOpts))
	return nil
}

// Convert_v1beta1_Filesystem_To_v1beta2_Filesystem is an autogenerated conversion function.
func Convert_v1beta1_Filesystem_To_v1beta2_Filesystem(in *Filesystem, out *v1beta2.Filesystem, s conversion.Scope) error {
	return autoConvert_v1beta1_Filesystem_To_v1beta2_Filesystem(in, out, s)
}

func autoConvert_v1beta2_Filesystem_To_v1beta1_Filesystem(in *v1beta2.Filesystem, out *Filesystem, s conversion.Scope) error {
	out.Device = in.Device
	out.Filesystem = in.Filesystem
	out.Label = in.Label
	out.Partition = (*string)(unsafe.Pointer(in.Partition))
	out.Overwrite = (*bool)(unsafe.Pointer(in.Overwrite))
	out.ReplaceFS = (*string)(unsafe.Pointer(in.ReplaceFS))
	out.ExtraOpts = *(*[]string)(unsafe.Pointer(&in.ExtraOpts))
	return nil
}

// Convert_v1beta2_Filesystem_To_v1beta1_Filesystem is an autogenerated conversion function.
func Convert_v1beta2_Filesystem_To_v1beta1_Filesystem(in *v1beta2.Filesystem, out *Filesystem, s conversion.Scope) error {
	return autoConvert_v1beta2_Filesystem_To_v1beta1_Filesystem(in, out, s)
}

func autoConvert_v1beta1_NTP_To_v1beta2_NTP(in *NTP, out *v1beta2.NTP, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1beta1_NTP_To_v1beta2_NTP is an autogenerated conversion function.
func Convert_v1beta1_NTP_To_v1beta2_NTP(in *NTP, out *v1beta2.NTP, s conversion.Scope) error {
	return autoConvert_v1beta1_NTP_To_v1beta2_NTP(in, out, s)
}

func autoConvert_v1beta2_NTP_To_v1beta1_NTP(in *v1beta2.NTP, out *NTP, s conversion.Scope) error {
	out.Servers = *(*[]string)(unsafe.Pointer(&in.Servers))
	out.Enabled = (*bool)(unsafe.Pointer(in.Enabled))
	return nil
}

// Convert_v1beta2_NTP_To_v1beta1_NTP is an autogenerated conversion function.
func Convert_v1beta2_NTP_To_v1beta1_NTP(in *v1beta2.NTP, out *NTP, s conversion.Scope) error {
	return autoConvert_v1beta2_NTP_To_v1beta1_NTP(in, out, s)
}

func autoConvert_v1beta1_Partition_To_v1beta2_Partition(in *Partition, out *v1beta2.Partition, s conversion.Scope) error {
	out.Device = in.Device
	out.Layout = in.Layout
	out.Overwrite = (*bool)(unsafe.Pointer(in.Overwrite))
	out.TableType = (*string)(unsafe.Pointer(in.TableType))
	return nil
}

// Convert_v1beta1_Partition_To_v1beta2_Partition is an autogenerated conversion function.
func Convert_v1beta1_Partition_To_v1beta2_Partition(in *Partition, out *v1beta2.Partition, s conversion.Scope) error {
	return autoConvert_v1beta1_Partition_To_v1beta2_Partition(in, out, s)
}

func autoConvert_v1beta2_Partition_To_v1beta1_Partition(in *v1beta2.Partition, out *Partition, s conversion.Scope) error {
	out.Device = in.Device
	out.Layout = in.Layout
	out.Overwrite = (*bool)(unsafe.Pointer(in.Overwrite))
	out.TableType = (*string)(unsafe.Pointer(in.TableType))
	return nil
}

// Convert_v1beta2_Partition_To_v1beta1_Partition is an autogenerated conversion function.
func Convert_v1beta2_Partition_To_v1beta1_Partition(in *v1beta2.Partition, out *Partition, s conversion.Scope) error {
	return autoConvert_v1beta2_Partition_To_v1beta1_Partition(in, out, s)
}

func autoConvert_v1beta1_PasswdSource_To_v1beta2_PasswdSource(in *PasswdSource, out *v1beta2.PasswdSource, s conversion.Scope) error {
	if err := Convert_v1beta1_SecretPasswdSource_To_v1beta2_SecretPasswdSource(&in.Secret, &out.Secret, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_PasswdSource_To_v1beta2_PasswdSource is an autogenerated conversion function.
func Convert_v1beta1_PasswdSource_To_v1beta2_PasswdSource(in *PasswdSource, out *v1beta2.PasswdSource, s conversion.Scope) error {
	return autoConvert_v1beta1_PasswdSource_To_v1beta2_PasswdSource(in, out, s)
}

func autoConvert_v1beta2_PasswdSource_To_v1beta1_PasswdSource(in *v1beta2.PasswdSource, out *PasswdSource, s conversion.Scope) error {
	if err := Convert_v1beta2_SecretPasswdSource_To_v1beta1_SecretPasswdSource(&in.Secret, &out.Secret, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta2_PasswdSource_To_v1beta1_PasswdSource is an autogenerated conversion function.
func Convert_v1beta2_PasswdSource_To_v1beta1_PasswdSource(in *v1beta2.PasswdSource, out *PasswdSource, s conversion.Scope) error {
	return autoConvert_v1beta2_PasswdSource_To_v1beta1_PasswdSource(in, out, s)
}

func autoConvert_v1beta1_PauseContainer_To_v1beta2_PauseContainer(in *PauseContainer, out *v1beta2.PauseContainer, s conversion.Scope) error {
	out.AccountNumber = in.AccountNumber
	out.Version = in.Version
	return nil
}

// Convert_v1beta1_PauseContainer_To_v1beta2_PauseContainer is an autogenerated conversion function.
func Convert_v1beta1_PauseContainer_To_v1beta2_PauseContainer(in *PauseContainer, out *v1beta2.PauseContainer, s conversion.Scope) error {
	return autoConvert_v1beta1_PauseContainer_To_v1beta2_PauseContainer(in, out, s)
}

func autoConvert_v1beta2_PauseContainer_To_v1beta1_PauseContainer(in *v1beta2.PauseContainer, out *PauseContainer, s conversion.Scope) error {
	out.AccountNumber = in.AccountNumber
	out.Version = in.Version
	return nil
}

// Convert_v1beta2_PauseContainer_To_v1beta1_PauseContainer is an autogenerated conversion function.
func Convert_v1beta2_PauseContainer_To_v1beta1_PauseContainer(in *v1beta2.PauseContainer, out *PauseContainer, s conversion.Scope) error {
	return autoConvert_v1beta2_PauseContainer_To_v1beta1_PauseContainer(in, out, s)
}

func autoConvert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(in *SecretFileSource, out *v1beta2.SecretFileSource, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource is an autogenerated conversion function.
func Convert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(in *SecretFileSource, out *v1beta2.SecretFileSource, s conversion.Scope) error {
	return autoConvert_v1beta1_SecretFileSource_To_v1beta2_SecretFileSource(in, out, s)
}

func autoConvert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(in *v1beta2.SecretFileSource, out *SecretFileSource, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource is an autogenerated conversion function.
func Convert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(in *v1beta2.SecretFileSource, out *SecretFileSource, s conversion.Scope) error {
	return autoConvert_v1beta2_SecretFileSource_To_v1beta1_SecretFileSource(in, out, s)
}

func autoConvert_v1beta1_SecretPasswdSource_To_v1beta2_SecretPasswdSource(in *SecretPasswdSource, out *v1beta2.SecretPasswdSource, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta1_SecretPasswdSource_To_v1beta2_SecretPasswdSource is an autogenerated conversion function.
func Convert_v1beta1_SecretPasswdSource_To_v1beta2_SecretPasswdSource(in *SecretPasswdSource, out *v1beta2.SecretPasswdSource, s conversion.Scope) error {
	return autoConvert_v1beta1_SecretPasswdSource_To_v1beta2_SecretPasswdSource(in, out, s)
}

func autoConvert_v1beta2_SecretPasswdSource_To_v1beta1_SecretPasswdSource(in *v1beta2.SecretPasswdSource, out *SecretPasswdSource, s conversion.Scope) error {
	out.Name = in.Name
	out.Key = in.Key
	return nil
}

// Convert_v1beta2_SecretPasswdSource_To_v1beta1_SecretPasswdSource is an autogenerated conversion function.
func Convert_v1beta2_SecretPasswdSource_To_v1beta1_SecretPasswdSource(in *v1beta2.SecretPasswdSource, out *SecretPasswdSource, s conversion.Scope) error {
	return autoConvert_v1beta2_SecretPasswdSource_To_v1beta1_SecretPasswdSource(in, out, s)
}

func autoConvert_v1beta1_User_To_v1beta2_User(in *User, out *v1beta2.User, s conversion.Scope) error {
	out.Name = in.Name
	out.Gecos = (*string)(unsafe.Pointer(in.Gecos))
	out.Groups = (*string)(unsafe.Pointer(in.Groups))
	out.HomeDir = (*string)(unsafe.Pointer(in.HomeDir))
	out.Inactive = (*bool)(unsafe.Pointer(in.Inactive))
	out.Shell = (*string)(unsafe.Pointer(in.Shell))
	out.Passwd = (*string)(unsafe.Pointer(in.Passwd))
	out.PasswdFrom = (*v1beta2.PasswdSource)(unsafe.Pointer(in.PasswdFrom))
	out.PrimaryGroup = (*string)(unsafe.Pointer(in.PrimaryGroup))
	out.LockPassword = (*bool)(unsafe.Pointer(in.LockPassword))
	out.Sudo = (*string)(unsafe.Pointer(in.Sudo))
	out.SSHAuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.SSHAuthorizedKeys))
	return nil
}

// Convert_v1beta1_User_To_v1beta2_User is an autogenerated conversion function.
func Convert_v1beta1_User_To_v1beta2_User(in *User, out *v1beta2.User, s conversion.Scope) error {
	return autoConvert_v1beta1_User_To_v1beta2_User(in, out, s)
}

func autoConvert_v1beta2_User_To_v1beta1_User(in *v1beta2.User, out *User, s conversion.Scope) error {
	out.Name = in.Name
	out.Gecos = (*string)(unsafe.Pointer(in.Gecos))
	out.Groups = (*string)(unsafe.Pointer(in.Groups))
	out.HomeDir = (*string)(unsafe.Pointer(in.HomeDir))
	out.Inactive = (*bool)(unsafe.Pointer(in.Inactive))
	out.Shell = (*string)(unsafe.Pointer(in.Shell))
	out.Passwd = (*string)(unsafe.Pointer(in.Passwd))
	out.PasswdFrom = (*PasswdSource)(unsafe.Pointer(in.PasswdFrom))
	out.PrimaryGroup = (*string)(unsafe.Pointer(in.PrimaryGroup))
	out.LockPassword = (*bool)(unsafe.Pointer(in.LockPassword))
	out.Sudo = (*string)(unsafe.Pointer(in.Sudo))
	out.SSHAuthorizedKeys = *(*[]string)(unsafe.Pointer(&in.SSHAuthorizedKeys))
	return nil
}

// Convert_v1beta2_User_To_v1beta1_User is an autogenerated conversion function.
func Convert_v1beta2_User_To_v1beta1_User(in *v1beta2.User, out *User, s conversion.Scope) error {
	return autoConvert_v1beta2_User_To_v1beta1_User(in, out, s)
}
